### ISSUE TITLE
Ignore heap-profiler functions on Flamegraph

### ISSUE THREAD

**Issue by RafaelGSS** [clinicjs/node-clinic-heap-profiler#47]
Currently, we are not ignoring the heap-profiler scripts in the analysis and it affects the entire flamegraph.

**Comment by mcollina** [comment]
how much? When I tested this it was not massive really

**Comment by RafaelGSS** [comment]
![image](https://user-images.githubusercontent.com/26234614/142286095-a8bdcfcb-7615-46c9-90fb-29dfd021860d.png)

Code:

```js
const Fastify = require('fastify')
const fastify = Fastify({ logger: true })

function soManyAllocations() {
  const A = [];
  for (let i = 0; i < 10000; i++) {
    A.push(new Array(2000));
  }
  return A;
}

fastify.get('/', (req, reply) => {
  const arr = soManyAllocations()
  reply.code(200).send('Hello World')
})

fastify.listen(3000, (err) => {
  if (err) throw err
})
```
```console
node-version: v16.6.0
command: clinic heapprofiler --autocannon [ / --method GET -d 120 ] -- node index.js
```

**Comment by mcollina** [comment]
Dang, let's just skip it.

**Comment by RafaelGSS** [comment]
I was looking at this issue in specific and I got some interesting findings:

If you run the script more than once you will get differing results, not entirely sure, but I think that it's due to some V8 optimizations in the first memory hits. Is that expected @mcollina? Well, it also might be because the script doesn't allocate big blocks of memory and it turns the graphs indeterministic? (Images at end)

I did a comparison with "Allocation Sampling" in the DevTools and the results look more consistent, however, it's important to mention that when I was running: `./bin.js heapprofiler --autocannon [ / --method GET ] -- node example.js` I was getting an autocannon result of: `520k requests in 11.01s, 85.8 MB read`.

But when I did the sampling in DevTools by running: `node --inspect example.js` -> start allocation sampling -> start autocannon the results were: `44k requests in 10.02s`.

Any thoughts? I'll keep going with tests before land #49.

### Samples HeapProfiler

#### Run 1
![image](https://user-images.githubusercontent.com/26234614/143869174-55256c4a-1ae3-4a74-9c1a-1f3f38cdc988.png)

#### Run 2
![image](https://user-images.githubusercontent.com/26234614/143869223-c85aaac3-bd9f-47d4-9f88-21b8ba165b65.png)

#### Run 3
![image](https://user-images.githubusercontent.com/26234614/143869269-0b1d732a-ebbd-4d20-a75e-f5a886fe06ec.png)

### Samples Allocation Timeline

#### Run 1

![image](https://user-images.githubusercontent.com/26234614/143874193-f1b808f6-8b3f-4d97-b23b-9cbbc8d0f47f.png)

#### Run 2

![image](https://user-images.githubusercontent.com/26234614/143874245-e1c261e0-7b30-44f5-9f00-a03cc5c30744.png)

#### Run 3

![image](https://user-images.githubusercontent.com/26234614/143874310-7a7824dc-9209-435c-8cb3-cb64eda84ff2.png)

---

Script utilized:

```js
const Fastify = require('fastify');
const app = Fastify({ logger: false })

app.get('/', function (req, res) {
  res.send('Ok')
})

app.listen(3000);
```
