### ISSUE TITLE
CI is not running properly on Pull Requests

### ISSUE THREAD

**Issue by RafaelGSS** [clinicjs/node-clinic-heap-profiler#48]
As titled.

**Comment by simoneb** [comment]
is it not? https://github.com/clinicjs/node-clinic-heap-profiler/blob/main/.github/workflows/ci.yml#L1

**Comment by RafaelGSS** [comment]
> is it not? https://github.com/clinicjs/node-clinic-heap-profiler/blob/main/.github/workflows/ci.yml#L1

That's weird because it was triggered neither in https://github.com/clinicjs/node-clinic-heap-profiler/pull/50 nor  https://github.com/clinicjs/node-clinic-heap-profiler/pull/45

**Comment by simoneb** [comment]
that's because actions are not enabled. this needs to be changed

**Comment by simoneb** [comment]
they were only enabled on a few repos. I have now enabled them on all repos across the org

**Comment by RafaelGSS** [comment]
Thanks!
