### ISSUE TITLE
walkthrough steps typos

### ISSUE THREAD

**Issue by victorhnogueira** [clinicjs/node-clinic-heap-profiler#69]
Some typos were found in the `src/visualizer/walkthrough-steps.js` file:

Line 33: "memorty"

```js
<p>This is a "hot" function - a lot of memorty was allocated by this function. The brighter the colour on the exposed top of a block, the "hotter" it is compared to the rest of the profile.</p>
```

line 87: "infomation"
```js
<p>For more infomation and detailed walkthroughs, see:</p> ${docs.outerHTML}
```

**Comment by victorhnogueira** [comment]
I tried to push the fixes but I don't have access to the repository

```
➜ git push origin fix/walkthrough-steps-typos
ERROR: Permission to clinicjs/node-clinic-heap-profiler.git denied to victorhnogueira.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by RafaelGSS** [comment]
You should:

1) fork the repository
2) clone the forked repository
3) create a new branch (as you did `fix/walkthrough-steps-typos`)
4) push this branch to the forked repository
5) create a pr against the main repository (it's pretty simple, when you enter in the main repository, you will see a button)

**Comment by victorhnogueira** [comment]
Thanks for guiding me @RafaelGSS.
